(#4513) Fix duplicated files in Debian packaging
puppet-dashboard.init, and puppet-dashboard.default were not getting
picked up, because default existed.

diff --git a/ext/packaging/debian/init b/ext/packaging/debian/init
--- a/ext/packaging/debian/init
+++ b/ext/packaging/debian/init
@@ -21,8 +21,16 @@ set -e
 test -f /etc/default/rcS && . /etc/default/rcS
 test -f /etc/default/puppet-dashboard && . /etc/default/puppet-dashboard
 
+# Set defaults in case they're not in the above defaults file:
+DASHBOARD_HOME=${DASHBOARD_HOME:-/usr/share/puppet-dashboard}
+DASHBOARD_USER=${DASHBOARD_USER:-www-data}
+DASHBOARD_RUBY=${DASHBOARD_RUBY:-/usr/bin/ruby}
+DASHBOARD_ENVIRONMENT=${DASHBOARD_ENVIRONMENT:-production}
+DASHBOARD_IFACE=${DASHBOARD_IFACE:-0.0.0.0}
+DASHBOARD_PORT=${DASHBOARD_PORT:-3000}
+
 check_dashboard_enabled_option() {
-    if [ ! "$dashboard_enabled" = "yes" ]; then
+    if [ ! "$START" = "yes" ]; then
         log_warning_msg "Not starting Puppet Dashboard, disabled via /etc/default/puppet-dashboard"
         return 1
     else
@@ -30,10 +38,30 @@ check_dashboard_enabled_option() {
     fi
 }
 
+check_puppet_dashboard_status() {
+    status_of_proc -p ${PIDFILE} ${DASHBOARD_RUBY} "Puppet Dashboard"
+}
+
+start_puppet_dashboard() {
+    start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile ${PIDFILE} --user ${DASHBOARD_USER} --chuid ${DASHBOARD_USER} --exec ${DASHBOARD_RUBY} -- ${DASHBOARD_HOME}/script/server -e ${DASHBOARD_ENVIRONMENT} -p ${DASHBOARD_PORT} -b ${DASHBOARD_IFACE} &
+
+    # This is a dirty, dirty hack, but it's rather difficult to get
+    # script/server to daemonize in any way, and still give us useful debugging
+    # output (or a real exit code) if it fails to start.
+
+    sleep 5
+
+    check_puppet_dashboard_status
+}
+
 case $1 in
     start)
         log_daemon_msg "Starting Puppet Dashboard"
-        if check_dashboard_enabled_option && start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --user puppet-dashboard --chuid puppet-dashboard --exec ${DASHBOARD_RUBY} -- ${DASHBOARD_HOME}/script/server -e ${DASHBOARD_ENVIRONMENT} >/dev/null 2>&1 ; then
+        if ! check_dashboard_enabled_option; then
+            log_end_msg 0
+            exit
+        fi
+        if start_puppet_dashboard; then
             log_end_msg 0
         else
             log_end_msg 1
@@ -41,7 +69,7 @@ case $1 in
     ;;
     stop)
         log_daemon_msg "Stopping Puppet Dashboard"
-        if start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE} --user puppet-dashboard -dashboard --retry 10; then
+        if start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE} --user ${DASHBOARD_USER} -dashboard --retry 10; then
             log_end_msg 0
         else
             log_end_msg 1
@@ -56,7 +84,11 @@ case $1 in
         case ${RET} in
             0)
                 # Old server stopped
-                if check_dashboard_enabled_option && start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --user puppet-dashboard --chuid puppet-dashboard --exec ${DASHBOARD_RUBY} -- ${DASHBOARD_HOME}/script/server -e ${DASHBOARD_ENVIRONMENT} >/dev/null 2>&1 ; then
+                if ! check_dashboard_enabled_option; then
+                    log_end_msg 0
+                    exit
+                fi
+                if start_puppet_dashboard; then
                     log_end_msg 0
                 else
                     log_end_msg 1
@@ -75,7 +107,7 @@ case $1 in
         esac
     ;;
     status)
-        status_of_proc -p ${PIDFILE} ${DASHBOARD_RUBY} "Puppet Dashboard" && exit 0 || exit $?
+        check_puppet_dashboard_status && exit 0 || exit $?
     ;;
     *)
         log_action_msg "Usage: /etc/init.d/puppet-dashboard {start|stop|restart|status}"
